export { default as Login } from './Login'
export { default as Cadastrar } from './Cadastrar'
export { default as Home } from './Home'
export { default as Diario } from './Diario'
export { default as Texto } from './Texto'
export { default as File } from './File'
export { default as Sair } from './Sair'
export { default as CadastraDiario } from './CadastraDiario'
